version: '3.8'

services:
  # =============================================================================
  # Backend Service
  # =============================================================================
  puntini-backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: puntini-backend
    ports:
      - "8025:8025"
    environment:
      # Backend environment variables (add your backend-specific variables here)
      - PYTHONPATH=/app
      - PORT=8025
    restart: unless-stopped
    networks:
      - puntini-network
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8025/docs')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # =============================================================================
  # Frontend Service
  # =============================================================================
  puntini-frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        # =============================================================================
        # API Configuration
        # =============================================================================
        - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:8025}
        - VITE_API_TIMEOUT=${VITE_API_TIMEOUT:-30000}
        - VITE_API_RETRY_ATTEMPTS=${VITE_API_RETRY_ATTEMPTS:-3}
        - VITE_API_RETRY_DELAY=${VITE_API_RETRY_DELAY:-1000}

        # =============================================================================
        # WebSocket Configuration
        # =============================================================================
        - VITE_WS_BASE_URL=${VITE_WS_BASE_URL:-ws://localhost:8025}
        - VITE_WS_RECONNECT_ATTEMPTS=${VITE_WS_RECONNECT_ATTEMPTS:-5}
        - VITE_WS_RECONNECT_DELAY=${VITE_WS_RECONNECT_DELAY:-2000}
        - VITE_WS_HEARTBEAT_INTERVAL=${VITE_WS_HEARTBEAT_INTERVAL:-30000}
        - VITE_WS_CONNECTION_TIMEOUT=${VITE_WS_CONNECTION_TIMEOUT:-10000}

        # =============================================================================
        # Authentication Configuration
        # =============================================================================
        - VITE_AUTH_TOKEN_STORAGE_KEY=${VITE_AUTH_TOKEN_STORAGE_KEY:-authToken}
        - VITE_AUTH_USER_STORAGE_KEY=${VITE_AUTH_USER_STORAGE_KEY:-authUser}
        - VITE_AUTH_TOKEN_EXPIRY_BUFFER=${VITE_AUTH_TOKEN_EXPIRY_BUFFER:-300000}

        # =============================================================================
        # UI Configuration
        # =============================================================================
        - VITE_UI_THEME=${VITE_UI_THEME:-light}
        - VITE_UI_LANGUAGE=${VITE_UI_LANGUAGE:-en}
        - VITE_UI_AUTO_SAVE=${VITE_UI_AUTO_SAVE:-true}
        - VITE_UI_AUTO_SAVE_INTERVAL=${VITE_UI_AUTO_SAVE_INTERVAL:-30000}

        # =============================================================================
        # Feature Flags
        # =============================================================================
        - VITE_FEATURES_DEBUG_MODE=${VITE_FEATURES_DEBUG_MODE:-false}
        - VITE_FEATURES_ANALYTICS_ENABLED=${VITE_FEATURES_ANALYTICS_ENABLED:-false}
        - VITE_FEATURES_OFFLINE_MODE=${VITE_FEATURES_OFFLINE_MODE:-false}
        - VITE_FEATURES_PUSH_NOTIFICATIONS=${VITE_FEATURES_PUSH_NOTIFICATIONS:-false}

        # =============================================================================
        # Development Configuration
        # =============================================================================
        - VITE_DEV_HOT_RELOAD=${VITE_DEV_HOT_RELOAD:-false}
        - VITE_DEV_SOURCE_MAPS=${VITE_DEV_SOURCE_MAPS:-false}
        - VITE_DEV_CONSOLE_LOGGING=${VITE_DEV_CONSOLE_LOGGING:-false}

        # =============================================================================
        # Application Environment
        # =============================================================================
        - NODE_ENV=${NODE_ENV:-production}
        - VITE_APP_ENV=${VITE_APP_ENV:-production}
    container_name: puntini-frontend
    ports:
      - "8026:8026"
    environment:
      - PORT=8026

    restart: unless-stopped
    networks:
      - puntini-network
    depends_on:
      puntini-backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8026', (res) => process.exit(res.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  puntini-network:
    driver: bridge
